OpenSLR Sundanese ASR
espnet/espnet pull request #3344
Opened 2021-07-09 05:33 UTC by peter-yh-wu

ASR for [OpenSLR Large Sundanese ASR training data set](http://www.openslr.org/36/)

2021-07-09 13:44 UTC, ftshijt requested changes
Thanks a lot. Just some minor issues

2021-07-09 13:44 UTC, ftshijt commented on egs2/sunda/asr1/setup.sh
> +../../TEMPLATE/asr1/setup.sh
We do not need this file for specific recipe

2021-07-09 13:44 UTC, ftshijt commented on egs2/sunda/asr1/run.sh
> +    --stage 2 \
Please set it as the initial setting (e.g., stage 1 )

2021-07-09 13:44 UTC, ftshijt commented on egs2/sunda/asr1/copy_files.sh
> +cp -r ../../alam6_wld/asr1/data/$1_test data/
Do we need this?

2021-07-09 13:44 UTC, ftshijt commented on egs2/sunda/asr1/local/score.sh
> +#!/bin/bash
If this is the same as https://github.com/espnet/espnet/blob/master/egs2/open_li52/asr1/local/score.sh you can use soft link for this

2021-07-09 13:44 UTC, ftshijt commented on egs2/sunda/asr1/run_eval.sh
> +lid=false # whether to use language id as additional label
Do we need this?

2021-07-09 13:44 UTC, ftshijt commented on egs2/sunda/asr1/run_wld.sh
> +train_set="train"
I don't think this shell script is necessary. If you think it is important, please share the reason

2021-07-09 15:58 UTC, ftshijt commented
Hi, Just a follow up to Shinji's advice, could you upload your model to espnet_model_zoo? You can check the steps here https://github.com/espnet/espnet_model_zoo

2021-07-09 17:03 UTC, ftshijt commented
Meanwhile, you may add a README in the Sundanese for results and pre-trained model (after you get the link from model_zoo

2021-07-12 19:57 UTC, sw005320 commented on egs2/su_openslr36/asr1/local/sunda_data_prep.py
> +import argparse
Please add an appropriate header (shebang and copyright)

2021-07-12 19:58 UTC, sw005320 approved these changes

2021-07-12 22:36 UTC, ftshijt commented
Since you already upload the model in model zoo, could you please also update the pre-trained link and results in RESULTS.md  (similar to https://github.com/espnet/espnet/tree/master/egs2/open_li52/asr1/README.md )

2021-07-12 22:37 UTC, ftshijt approved these changes

2021-07-13 01:05 UTC, merged