[WIP] ESPnet2 CMU ARCTIC VC
espnet/espnet pull request #3792
Opened 2021-11-16 07:27 UTC by peter-yh-wu

2021-12-21 01:27 UTC, sw005320 commented
@peter-yh-wu, Is this still WIP?
If it is ready, can you remove WIP in the PR title?
Can you also fix the CI error?

@kan-bayashi, after @peter-yh-wu, fixes them, can you make a PR?

2021-12-22 12:50 UTC, sw005320 commented
@peter-yh-wu, we still observe some CI errors

2021-12-22 12:51 UTC, kan-bayashi commented
Sorry for the late review. I can do it in this weekend.

2021-12-22 13:13 UTC, kan-bayashi requested changes
(This is the 1st quick review.)

Thank you for your great PR.
It seems that this PR still includes unnecessary files.
Please remove files which is not used.
And the template still includes TTS related parts.
Please remove them.

2021-12-22 13:13 UTC, kan-bayashi commented on espnet2/bin/vc_inference.py
> +        >>>     vocoder_tag="kan-bayashi/ljspeech_tacotron2",
tag example may be different.

2021-12-22 13:13 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +                ${python} -m "espnet2.bin.tts_train" \
```suggestion
                ${python} -m "espnet2.bin.vc_train" \
```

2021-12-22 13:13 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/conf/ob_eval/decode_asr.yaml
> +batchsize: 0
may not need.

2021-12-22 13:13 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/conf/pitch.conf
> +--sample-frequency=16000
may not need.

2021-12-22 13:13 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/conf/fbank.conf
> +--sample-frequency=16000
may not need.

2021-12-22 13:13 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/conf/tuning/train_tacotron2.yaml
> +# This configuration is for ESPnet2 to train Tacotron 2. Compared to the
may not need.

2021-12-22 13:13 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/conf/tuning/train_conformer_fastspeech2.yaml
> +# This configuration is for ESPnet2 to train Conformer-based
may not need.

2021-12-22 13:13 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/conf/tuning/decode_fastspeech.yaml
> +# This configuration is the decoding setting for FastSpeech or FastSpeech2.
may not need.

2021-12-22 13:13 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/conf/specaug.yaml
> +process:
may not need.

2021-12-22 13:13 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/local/ob_eval/evaluate.sh
> +#!/usr/bin/env bash
may not need.

2021-12-22 13:13 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/local/ob_eval/data_prep_for_asr.sh
> +#!/usr/bin/env bash
may not need.

2021-12-22 13:13 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/local/pretrained_model_download.sh
> +#!/usr/bin/env bash
Did you use it?

2021-12-22 13:19 UTC, kan-bayashi commented
And I recommend making the template vc.sh simpler (e.g., removed unused parts as the first step).

2021-12-27 06:33 UTC, peter-yh-wu commented on egs2/TEMPLATE/vc1/vc.sh
> +                         # Note that multiple items can be specified.
Some VC models seem to use ASR to improve the model so I kept this `srctexts` option. Definitely can remove this though if we won't try those approaches.

2021-12-27 06:33 UTC, peter-yh-wu commented on egs2/TEMPLATE/vc1/vc.sh
> +srctexts=""      # Texts to create token list. Multiple items can be specified.
Some VC models seem to use ASR to improve the model so I kept this `srctexts` option. Definitely can remove this though if we won't try those approaches.

2021-12-27 06:33 UTC, peter-yh-wu commented on egs2/TEMPLATE/vc1/vc.sh
> +    fi
(Some VC models seem to use ASR to improve the model so I kept this `srctexts` option. Definitely can remove this though if we won't try those approaches.)

2022-02-02 22:18 UTC, ftshijt commented
Could you pull the latest master in espnet so as to fix the broken CI?

2022-02-03 00:59 UTC, kan-bayashi requested changes
Sorry for too late reviewing...
For shellscript, please use shellcheck to reduce minor errors.
There are still unused options and arguments.
Please carefully check again.

And I want to make the names consistent.
E.g., You used in_speech and out_speech so
- feats_extract -> in_feats_extract
- output_feats_extract -> out_feats_extract

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +vc_stats_dir=""   # Specify the directory path for statistics. If empty, automatically decided.
```suggestion
vc_exp=""          # Specify the directory path for experiment. If this option is specified, tag is ignored.
vc_stats_dir=""    # Specify the directory path for statistics. If empty, automatically decided.
```

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +
Not needed.
```suggestion
```

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +lang=noinfo      # The language type of corpus.
```suggestion
lang=noinfo         # The language type of corpus.
```

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +    --sos_eos          # sos and eos symbole (default="${sos_eos}").
Not needed.
```suggestion
```

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +    --nlsyms_txt         # Non-linguistic symbol list (default="${nlsyms_txt}").
Not needed.
```suggestion
```

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +        for i in "${!src_test_sets[@]}"; do
I think `src_test_sets` is not array, which is just string separated with space.
Does it work?

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +        for i in "${!src_test_sets[@]}"; do
ditto

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +        # NOTE(peter): skipped Prepare lang id input
It is better to show messages.
```suggestion
        # NOTE(peter): skipped Extract X-vector
        if "${use_xvector}"; then
            log "[ERROR] X-vector is not supported yet."
            exit 1
        fi
        # NOTE(peter): skipped Prepare spk id input
        if "${use_sid}"; then
            log "[ERROR] Speaker ID is not supported yet."
            exit 1
        fi
        # NOTE(peter): skipped Prepare lang id input
        if "${use_lid}"; then
            log "[ERROR] Language ID is not supported yet."
            exit 1
        if
```

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +                --non_linguistic_symbols "${nlsyms_txt}" \
May not be needed.
```suggestion
```

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +                for i in $(seq "${_nj}"); do
`i` is reused within for loop.

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +        log "Stage 9: Upload model to Zenodo: ${packed_model}"
`packed_model` is not defined.

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/TEMPLATE/vc1/vc.sh
> +            for i in $(seq "${_nj}"); do
`i` is reused within for loop.

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/conf/rms.f0
> +55 200
This file may not be needed.

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/conf/slt.f0
> +120 275
This file may not be needed.

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/conf/bdl.f0
> +70 210
This file may not be needed.

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/conf/clb.f0
> +110 270
This file may not be needed.

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/prev/run_0-egs.sh
> +#!/usr/bin/env bash
This file may not be needed.

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/run.sh
> +    --g2p "${g2p}" \
Please carefully check the arguments.
```suggestion
```

2022-02-03 00:59 UTC, kan-bayashi commented on egs2/cmu_arctic/vc1/run.sh
> +    --srctexts "data/${src_train_set}/text" \
```suggestion
```

2022-02-03 00:59 UTC, kan-bayashi commented on espnet2/tasks/vc.py
> +        )
May not be needed.
```suggestion
```

2022-02-03 00:59 UTC, kan-bayashi commented on espnet2/tasks/vc.py
> +        )
May not be needed.
```suggestion
```

2022-02-03 00:59 UTC, kan-bayashi commented on espnet2/tasks/vc.py
> +                g2p_type=args.g2p,
May not be needed.
```suggestion
```

2022-02-03 00:59 UTC, kan-bayashi commented on espnet2/tasks/vc.py
> +            retval = ("text", "spembs", "out_speech", "durations", "sids", "lids")
```suggestion
            retval = ("spembs", "durations", "pitch", "energy", "sids", "lids")
        else:
            # Inference mode
            retval = ("spembs", "out_speech", "durations", "sids", "lids")
```

2022-02-03 00:59 UTC, kan-bayashi commented on espnet2/tasks/vc.py
> +
May not be needed.
```suggestion
```

2022-02-03 00:59 UTC, kan-bayashi commented on espnet2/tasks/vc.py
> +            energy_normalize = energy_normalize_class(**args.energy_normalize_conf)
If we use these extractors, it should not be shared between src trg spks as well as feats_extract.

2022-02-03 00:59 UTC, kan-bayashi commented on espnet2/vc/transformer/transformer.py
> +        olens: torch.Tensor,
Why don't you use in_speech, ...  instead?

2022-02-03 00:59 UTC, kan-bayashi commented on espnet2/vc/abs_vc.py
> +        olens: torch.Tensor,
Why don't you use in_speech... instead?

2022-02-03 00:59 UTC, kan-bayashi commented on espnet2/vc/espnet_model.py
> +        )
ditto

2022-02-03 06:14 UTC, ftshijt reviewed
Some minor issues

2022-02-03 06:14 UTC, ftshijt commented on egs2/TEMPLATE/vc1/conf/mfcc.conf
> +--sample-frequency=16000
Just curious, is this a recommended setting for vc as well?

2022-02-03 06:14 UTC, ftshijt commented on egs2/TEMPLATE/vc1/setup.sh
> +target=../../TEMPLATE/tts1/path.sh
since you already has a templdate in vc, how about symlink to there (I understand it's exactly the same for now, but just in case)

2022-02-03 06:14 UTC, ftshijt commented on egs2/TEMPLATE/vc1/vc.sh
> +                    --train_data_path_and_name_and_type "${_train_dir}/text,text,text" \
Is text used here?

2023-07-20 13:24 UTC, closed without merging