[TTS] Support python-based toolkit for xvector extractors
espnet/espnet pull request #4016
Opened 2022-01-31 12:41 UTC by Fhrozen

@sw005320 
I was playing with speechbrain and maybe while the diarization part of ESPnet is still ongoing, we may use speechbrain as a toolkit for speaker embeddings, instead of kaldi.
Reduces the need to extract MFCC, VAD.

I am PR this draft, let me know if it is useful.

2022-02-01 05:54 UTC, kan-bayashi requested changes
Thank you for your great PR.
It is very nice but I have some comments especially about naming and stages.
Please check them.

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
> +            if [ "${xv_tool}" == "kaldi" ]; then
In test command, string comparison is =, not ==.
```suggestion
            if [ "${xv_tool}" = "kaldi" ]; then
```

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
> +xv_model=speechbrain/spkrec-ecapa-voxceleb  # kaldi: http://kaldi-asr.org/models/8/0008_sitw_v2_1a.tar.gz
I do not like too short variable name.
Why don't you use 
- xv_tool -> xvector_tool
- xv_model -> xvector_model
- sb -> speechbrain
- esp -> espnet

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
> +xv_model=speechbrain/spkrec-ecapa-voxceleb  # kaldi: http://kaldi-asr.org/models/8/0008_sitw_v2_1a.tar.gz
And I want to keep the default behavior since many recipe instruction follows kaldi version.

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
> +    --xv_model      # Pretrained model to generate the X-vectors (default="${xv_model}").
Ditto

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
> +    if [ ${stage} -le 3 ] && [ ${stop_stage} -ge 3 ]; then
I understand the motivation of separating this stage.
However, we need to fix all of the documents, which is too heavy.
Could you keep it as it?

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
> +                                                                ${dumpdir}/xvector/${dset}
```suggestion
                    pyscripts/utils/extract_xvectors.py \
                        --pretrained ${xv_model} \
                        --toolkit ${xv_tool} \
                        ${data_feats}/${dset} \
                        ${dumpdir}/xvector/${dset}
```

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/vctk/tts1/conf/tuning/train_xvector_vits_sb.yaml
> +# This configuration is for ESPnet2 to train multi-speaker
Personally, I like `train_speechbrain_xvector_vits.yaml`.

2022-02-01 05:54 UTC, kan-bayashi commented on tools/installers/install_speechbrain.sh
> +            echo "ERROR: pytorch version <1.8.0"
```suggestion
            echo "ERROR: speechbrain requires pytorch version >= 1.8.0"
            exit 1
```

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/TEMPLATE/asr1/pyscripts/utils/extract_xvectors.py
> +        type=str,
Why don't you add choices here?

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/TEMPLATE/asr1/pyscripts/utils/extract_xvectors.py
> +        help="Verbosity level."
Typo.

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/TEMPLATE/asr1/pyscripts/utils/extract_xvectors.py
> +    if args.toolkit == 'sb':
ditto

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/TEMPLATE/asr1/pyscripts/utils/extract_xvectors.py
> +    elif args.toolkit == 'esp':
ditto

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/TEMPLATE/asr1/pyscripts/utils/extract_xvectors.py
> +        help="Path to the input data."
```suggestion
        help="Path to the input kaldi data directory."
```

2022-02-01 05:54 UTC, kan-bayashi commented on egs2/TEMPLATE/asr1/pyscripts/utils/extract_xvectors.py
> +        "--pretrained",
I want to make it consistent in naming.
```suggestion
        "--pretrained_model",
```

2022-02-01 15:56 UTC, Fhrozen commented
@kan-bayashi, updated. 
Let me know for any comment.

2022-02-02 00:30 UTC, kan-bayashi requested changes

2022-02-02 00:30 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
> +xvector_model=speechbrain/spkrec-ecapa-voxceleb  # for espnet or speechbrain
```suggestion
use_xvector=false   # Whether to use x-vector.
xvector_tool=kaldi  # Toolkit for extracting x-vector (speechbrain, espnet, kaldi)
xvector_model=speechbrain/spkrec-ecapa-voxceleb  # For only espnet or speechbrain
```

2022-02-02 00:30 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
> +    --xvector_model     # Pretrained model to generate the X-vectors (default="${xvector_model}").
```suggestion
    --use_xvector      # Whether to use X-vector (default="${use_xvector}").
    --xvector_tool     # Toolkit for generating the X-vectors (default="${xvector_tool}").
    --xvector_model    # Pretrained model to generate the X-vectors (default="${xvector_model}").
```

2022-02-02 00:30 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
> +                            ${dumpdir}/xvector/${dset}
Please follow the space 4 indent.
```suggestion
                    pyscripts/utils/extract_xvectors.py \
                        --pretrained_model ${xvector_model} \
                        --toolkit ${xvector_tool} \
                        ${data_feats}/${dset} \
                        ${dumpdir}/xvector/${dset}
```

2022-02-02 00:30 UTC, kan-bayashi commented on tools/installers/install_speechbrain.sh
> +    touch speechbrain.done
```suggestion
    if "${torch_18_plus}"; then
        python3 -m pip install speechbrain==0.5.11
        touch speechbrain.done
    else
        echo "[ERROR]: speechbrain requires pytorch>=1.8.0"
        exit 1
    fi
```

2022-02-02 02:55 UTC, kan-bayashi commented on tools/installers/install_speechbrain.sh
> +
@Fhrozen It seems we need to make commit and push in local to launch ci.
Could you remove this part and do it?

2022-02-02 22:14 UTC, ftshijt commented
Could you pull the latest master in espnet so as to fix the broken CI?

2022-02-03 00:01 UTC, kan-bayashi approved these changes
LGTM! Thank you for great PR.

2022-02-03 06:04 UTC, ftshijt commented
Since already been approved by @kan-bayashi, I will merge it. Many thanks!

2022-02-03 06:04 UTC, merged