Fix joint tokenization in st.sh
espnet/espnet pull request #4143
Opened 2022-03-07 05:21 UTC by pyf98

Hi, in `st.sh`, the source and target texts should be merged before tokenization, if `token_joint` is `True`.

This modification is based on the same stage in `mt.sh`. Please check if it's correct.

2022-03-07 05:28 UTC, ftshijt commented
Looks cool to me, I will merge it after CI passed. Many thanks!

2022-03-07 06:39 UTC, siddalmia requested changes
https://github.com/espnet/espnet/blob/3ae0dcc9442981274a98ab4cd375e381e4e2b491/egs2/TEMPLATE/st1/st.sh#L299-L307

This will no longer be needed.

2022-03-08 00:08 UTC, pyf98 commented
> https://github.com/espnet/espnet/blob/3ae0dcc9442981274a98ab4cd375e381e4e2b491/egs2/TEMPLATE/st1/st.sh#L299-L307
> 
> This will no longer be needed.

Thanks for pointing it out. I removed these lines. Could you review it again?

2022-03-08 01:09 UTC, siddalmia commented
Looks good!

2022-03-08 20:13 UTC, merged