add e2e tts model: JETS
espnet/espnet pull request #4364
Opened 2022-05-13 13:55 UTC by imdanboy

Hi, thanks for your great works; espnet

I experimented the e2e tts model (JETS) recently following 
paper: https://arxiv.org/abs/2203.16852
code: https://github.com/imdanboy/jets
and get some reasonable results on ljspeech, kss dataset.

Most part of the code is based on fastspeech2 and hifi-gan of espnet. It would be honor if it can be implemented in espnet.
I think an alignment module, related to an text-speech alignment learning, would be helpful at least to simplify the training of non-autoregressive tts model such as fastspeech.

Thanks.

2022-05-14 01:27 UTC, kan-bayashi requested changes
Thank you for your contribution.
This is really cool :) 
I have some requests:
- Could you fix CI errors? https://github.com/espnet/espnet/runs/6424148362?check_suite_focus=true 
- Could you add unit test for JETS modules 
  E.g., https://github.com/espnet/espnet/blob/afa8f8ec5b8ec77deb1a3c1531915ebbee7b80e6/test/espnet2/gan_tts/vits/test_vits.py#L280-L343

https://github.com/espnet/espnet/blob/master/CONTRIBUTING.md#41-python
This document will help you.

2022-05-15 23:57 UTC, kan-bayashi reviewed
Thank you so much your kind modification.
Almost good for me but could you check my minor comments?

2022-05-15 23:57 UTC, kan-bayashi commented on espnet2/gan_tts/jets/generator.py
> +"""
```suggestion
"""Generator module in JETS."""
```

2022-05-15 23:57 UTC, kan-bayashi commented on espnet2/gan_tts/jets/loss.py
> +            blank_prob (float): Blank symbol probability
```suggestion
            blank_prob (float): Blank symbol probability.
```

2022-05-15 23:57 UTC, kan-bayashi commented on espnet2/gan_tts/jets/length_regulator.py
> +            Tensor: Expanded hidden state (B, T_feat, adim)
```suggestion
            hs (Tensor): Batched hidden state to be expanded (B, T_text, adim).
            ds (Tensor): Batched token duration (B, T_text).
            h_masks (Tensor): Mask tensor (B, T_feats).
            d_masks (Tensor): Mask tensor (B, T_text).

        Returns:
            Tensor: Expanded hidden state (B, T_feat, adim).
```

2022-05-15 23:57 UTC, kan-bayashi commented on espnet2/gan_tts/jets/alignments.py
> +import numpy as np
Add your credit?

2022-05-15 23:57 UTC, kan-bayashi commented on espnet2/gan_tts/jets/generator.py
> +# Copyright 2021 Tomoki Hayashi
Change to your credit?

2022-05-15 23:57 UTC, kan-bayashi commented on espnet2/gan_tts/jets/jets.py
> +# Copyright 2021 Tomoki Hayashi
Change to your credit?

2022-05-15 23:57 UTC, kan-bayashi commented on espnet2/gan_tts/jets/length_regulator.py
> +import logging
Add your credit?

2022-05-16 11:36 UTC, imdanboy commented
> Thank you so much your kind modification. Almost good for me but could you check my minor comments?

Thank you for your kind reply!
I've reflected your comments :)

2022-05-16 12:05 UTC, kan-bayashi commented on test/espnet2/gan_tts/jets/test_jets.py
> +# Copyright 2021 Tomoki Hayashi
```suggestion
# Copyright 2022 Dan Lim
```

2022-05-16 12:05 UTC, kan-bayashi commented on espnet2/gan_tts/jets/loss.py
> +# Copyright 2020 Nagoya University (Tomoki Hayashi)
```suggestion
# Copyright 2022 Dan Lim
```

2022-05-16 12:12 UTC, kan-bayashi commented on espnet2/gan_tts/jets/alignments.py
> +            Tensor: log probability of attention matrix (B, T_feats, T_text)
```suggestion
            text (Tensor): Batched text embedding (B, T_text, adim).
            feats (Tensor): Batched acoustic feature (B, T_feats, odim).
            x_masks (Tensor): Mask tensor (B, T_text).

        Returns:
            Tensor: Log probability of attention matrix (B, T_feats, T_text).
```

2022-05-16 12:12 UTC, kan-bayashi commented on espnet2/gan_tts/jets/alignments.py
> +        Tensor: binarization loss tensor ()
```suggestion
        log_p_attn (Tensor): Batched log probability of attention
            matrix (B, T_feats, T_text).
        text_lengths (Tensor): Text length tensor (B,).
        feats_legnths (Tensor): Feature length tensor (B,).

    Returns:
        Tensor: Batched token duration extracted from `log_p_attn` (B, T_text).
        Tensor: Binarization loss tensor ().
```

2022-05-16 12:12 UTC, kan-bayashi commented on espnet2/gan_tts/jets/alignments.py
> +        Tensor: Batched feature averaged according to the token duration (B, T_text)
```suggestion
        ds (Tensor): Batched token duration (B, T_text).
        xs (Tensor): Batched feature sequences to be averaged (B, T_feats).
        text_lengths (Tensor): Text length tensor (B,).
        feats_lengths (Tensor): Feature length tensor (B,).

    Returns:
        Tensor: Batched feature averaged according to the token duration (B, T_text).
```

2022-05-16 12:12 UTC, kan-bayashi commented on espnet2/gan_tts/jets/generator.py
> +            Tensor: ground-truth averaged energy (B,T_text,1)
```suggestion
            Tensor: Waveform tensor (B, 1, segment_size * upsample_factor).
            Tensor: Binarization loss ().
            Tensor: Log probability attention matrix (B, T_feats, T_text).
            Tensor: Segments start index tensor (B,).
            Tensor: predicted duration (B, T_text).
            Tensor: ground-truth duration obtained from an alignment module (B, T_text).
            Tensor: predicted pitch (B, T_text,1).
            Tensor: ground-truth averaged pitch (B, T_text, 1).
            Tensor: predicted energy (B, T_text, 1).
            Tensor: ground-truth averaged energy (B, T_text, 1).
```

2022-05-16 12:12 UTC, kan-bayashi commented on espnet2/gan_tts/jets/loss.py
> +            Tensor: Batched 2d static prior matrix (B, T_feats, T_text)
```suggestion
            w (float): Scaling factor; lower -> wider the width.

        Returns:
            Tensor: Batched 2d static prior matrix (B, T_feats, T_text).
```

2022-05-16 12:14 UTC, kan-bayashi approved these changes
Thank you for your modification!
I sightly fixed minor issues.
If the CI is passed, I will merge this great PR :)

2022-05-16 16:17 UTC, imdanboy commented
@sw005320, Sure! I will do your suggestion soon :)

2022-05-16 23:13 UTC, merged

2022-05-17 00:32 UTC, kan-bayashi commented
@imdanboy I updated README #4369.
If you can the pretrained models, that is great!