Update Muskit migration
espnet/espnet pull request #4463
Opened 2022-06-22 02:41 UTC by A-Quarter-Mile

Hi, here are new updates on muskit migration.

1. Add muskit installation.
- install by using 'tools/installer/install_muskit.sh

2. Add svs TEMPLATE.
- Update svs README.md

2022-06-24 04:12 UTC, ftshijt requested changes
I think the most urgent step for now is to determine the final data format and preparation pipeline. Several issues:
1.  In original Muskits, we prepare the `segments` but do not prepare midi.scp (in utt level) until format_scp.sh
2. We need to discuss whether to use midi or musicxml. musicxml is more readable and could potentially contain more information. The alignment can be explicit noted. So I  would suggest to use that. However, that means that we need to rewrite the interface.

2022-06-24 04:12 UTC, ftshijt commented on egs2/TEMPLATE/svs1/README.md
> +    │   ├── midi.scp   # MIDI file path
I think we should re-design the data format, especially for label file, which is difficult to read or analysis

2022-06-24 04:12 UTC, ftshijt commented on egs2/TEMPLATE/svs1/db.sh
> +# Set the path of your corpus
Maybe we can combine it with the asr's? (then we can just use a sym-link)

2022-06-24 04:12 UTC, ftshijt commented on egs2/TEMPLATE/svs1/db.sh
> +# Set the path of your corpus
Individual might be a good choice though, since we are somewhat different, and it can keep the file simpler. We can have some discussion later.

2022-06-24 04:12 UTC, ftshijt commented on egs2/TEMPLATE/svs1/pyscripts/audio/format_midi_scp.py
> +#!/usr/bin/env python3
Depends on the data format, we may rewrite it

2022-06-24 04:12 UTC, ftshijt commented on egs2/TEMPLATE/svs1/pyscripts/audio/midi_extraction.py
> +#!/usr/bin/env python3
Ditto, if we use musicxml, we may change the interface a bit

2022-06-24 04:12 UTC, ftshijt commented on egs2/TEMPLATE/svs1/pyscripts/utils/evaluate_f0.py
> +#!/usr/bin/env python3
we already have it in tts1, please use sym-link for this file

2022-06-24 04:12 UTC, ftshijt commented on egs2/TEMPLATE/svs1/pyscripts/utils/prep_segments.py
> +#!/usr/bin/env python3
We can discuss with others for the segmentation later. But this still can be a default one. Recommend to add some comments in the file to make it clear for usage

2022-06-24 04:12 UTC, ftshijt commented on egs2/TEMPLATE/svs1/scripts/audio/format_scp.sh
> +#!/usr/bin/env bash
The same, depends on the interface, this file might change.

2022-06-24 04:12 UTC, ftshijt commented on egs2/TEMPLATE/svs1/scripts/utils/combine_data.sh
> +#!/usr/bin/env bash
This is a modified version of kaldi combine data which has support to music data. We can discuss if it is necessary

2022-06-24 04:12 UTC, ftshijt commented on egs2/TEMPLATE/svs1/scripts/utils/copy_data_dir.sh
> +#!/usr/bin/env bash
Ditto

2022-06-24 04:12 UTC, ftshijt commented on tools/installers/install_muskit.sh
> +cd ParallelWaveGAN
Is ParallelWaveGAN the only file to be loaded? I thought we also have some other packages (e.g., miditoolkit)

2022-07-01 00:28 UTC, ftshijt reviewed
As mentioned, many parts should be refactored this time, please hold them for discussion. Current code style is not neat

2022-07-01 00:28 UTC, ftshijt commented on espnet2/fileio/sound_scp.py
> +        if pitch_aug_factor != 0:
This is a bit ugly, need to refactor to an augmentation layer instead of directly conduct in sound_scp fileio

2022-07-01 00:28 UTC, ftshijt commented on espnet2/fileio/read_text.py
> +def load_label_sequence(path: Union[Path, str]) -> Dict[str, List[Union[float, int]]]:
As mentioned, we should redefine the file structure. Current one is not good

2022-07-01 00:28 UTC, ftshijt commented on espnet2/fileio/utils.py
> +def midi_to_seq(
need to be discussed

2022-07-01 00:28 UTC, ftshijt commented on espnet2/main_funcs/collect_stats.py
> +                    "pitch_aug_lengths",
we should consider change this part

2022-07-10 17:58 UTC, sw005320 commented
Hi @A-Quarter-Mile, can you work on reflecting @ftshijt's comments?

2022-07-10 18:34 UTC, ftshijt commented
> Hi @A-Quarter-Mile, can you work on reflecting @ftshijt's comments?

@A-Quarter-Mile Yeah, please try to incrementally add your changes to the branch (feel free to open multiple PRs for each of the major stages, like installation, task definition, recipe template). 

@sw005320 FYI: we are having weekly meeting on the migration. @A-Quarter-Mile is working on some interface changing towards the migration to support a neater recipe layout (i.e., merge lyric alignment and music score info into musicxml format, so that we won't need two additional files for each recipe). After the change, we expect the interface could be further used for more music tasks (e.g., music generation, music transcription, etc.) not limited to singing voice synthesis

2022-07-10 18:47 UTC, sw005320 commented
OK, cool!

2022-07-12 14:41 UTC, closed without merging