Adding MFA scripts
espnet/espnet pull request #4557
Opened 2022-08-04 15:04 UTC by iamanigeeit

This commit adds scripts necessary to convert MFA to ESPnet formats.

- `mfa.sh` automates the entire conversion process
- `tts.sh` has been modified to pass arguments to `data.sh` for MFA
- `data.sh` has been edited to produce required text and durations files

To create .lab files for other datasets, define the relevant function in `mfa_format.py`.

2022-08-08 13:08 UTC, kan-bayashi requested changes
Sorry for the late reviewing and thank you for adding cool features!
Could you reflect my comments and fix the CI errors?

2022-08-08 13:08 UTC, kan-bayashi commented on egs2/TEMPLATE/asr1/scripts/utils/mfa.sh
> +# conda install montreal-forced-aligner
```suggestion
#!/usr/bin/env bash

# Generate MFA alignement

# You need to install the following tools to run this script:
# $ conda config --append channels conda-forge
# $ conda install montreal-forced-aligner

# If you are not using LJSpeech, be sure to define how your 
# dataset is processed in `scripts/utils/mfa_format.py`.

set -e
```

2022-08-08 13:08 UTC, kan-bayashi commented on egs2/ljspeech/tts1/run_mfa.sh
> +# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
And if you make separated script, I think it is better to add all options in this scripts in order to train by just executing `./run_mfa.sh`.

2022-08-08 13:08 UTC, kan-bayashi commented on egs2/TEMPLATE/asr1/scripts/utils/mfa.sh
> +
```suggestion

echo "Successfully finished generating MFA alignments.

# NOTE(iamanigeeit): If you want to train FastSpeech2 with the alignments, 
# please check `egs2/ljspeech/tts1/run_mfa.sh` as an example.
```

2022-08-08 13:08 UTC, kan-bayashi commented on egs2/TEMPLATE/asr1/scripts/utils/mfa_format.py
> +'''
```suggestion
#!/usr/bin/env python3

"""Convert files to/from MFA format for use in ESPnet TTS.

If you wish to add functions to create .lab files for MFA, add them like this:

def make_labs_[dataset]:
     ...
"""
```

2022-11-14 11:43 UTC, iamanigeeit commented
@kan-bayashi Sorry for the delay because of ICASSP submission. I will pull the latest version of ESPnet and fix my PR this week!

2022-11-29 12:01 UTC, iamanigeeit commented
Hello @kan-bayashi 

I have made the requested changes, but i can't submit the PR, because i have modified other files for my own work on `iamanigeeit:master`.

I tried to fork `espnet` again, but i am only allowed to fork once. When i create a new branch `iamanigeeit:espnet/mfa` and try to create a new PR from there, i get

> Can't create a new pull request: Although you appear to have the correct authorization credentials, the `espnet` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited.

What should i do?

2022-11-29 13:14 UTC, kan-bayashi commented
Thank you for your modification, @iamanigeeit.

> Can't create a new pull request: Although you appear to have the correct authorization credentials, the espnet organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited.

I've never met this kind of error. Let me confirm your procedure.

1. make new branch and perform cherry-pick in your local
2. push your branch to your fork `iamanigeeit/espnet`.
3. make PR from github HP

Is it correct?

2022-12-02 07:59 UTC, iamanigeeit commented
Thanks @kan-bayashi 

Creating a new branch and making the PR from Github instead of Pycharm seems to work. The new commit is at https://github.com/espnet/espnet/pull/4801

2022-12-02 07:59 UTC, closed without merging