Fix both utt2sid and utt2lid when removing long/short data
espnet/espnet pull request #4609
Opened 2022-08-30 13:27 UTC by jonghwanhyeon

Stage 3 of `tts.sh` removes long/short data. At this time, authors use `utils/fix_data_dir.sh` to remove the entry of the removed utterance as follows:

https://github.com/espnet/espnet/blob/e5d133c21800116b2fc5844859333ef83163d293/egs2/TEMPLATE/tts1/tts.sh#L500-L509

However, if there exist both `utt2sid` and `utt2lid`, `_fix_opts` are overwritten as `"--utt_extra_files utt2lid "` because authors used the assignment operator. So I tried to fix the above code as follows:

```bash
# fix_data_dir.sh leaves only utts which exist in all files
_fix_opts=""
if [ -e "${data_feats}/org/${dset}/utt2sid" ]; then
    _fix_opts+="--utt_extra_files utt2sid "
fi
if [ -e "${data_feats}/org/${dset}/utt2lid" ]; then
    _fix_opts+="--utt_extra_files utt2lid "
fi
# shellcheck disable=SC2086
utils/fix_data_dir.sh ${_fix_opts} "${data_feats}/${dset}"
```

However, after I tested it, it seems that `utils/fix_data_dir.sh` does not support multiple options. So, I suggest the following workaround in this PR becuase `utils/fix_data_dir.sh` is a part of `kaldi`:
```bash
# fix_data_dir.sh leaves only utts which exist in all files
if [ -e "${data_feats}/org/${dset}/utt2sid" ]; then
    utils/fix_data_dir.sh --utt_extra_files utt2sid "${data_feats}/${dset}"
fi
if [ -e "${data_feats}/org/${dset}/utt2lid" ]; then
    utils/fix_data_dir.sh --utt_extra_files utt2lid "${data_feats}/${dset}"
fi
```

2022-09-02 00:20 UTC, kan-bayashi requested changes
Thank you for your report and fixing.
In your case, the fixing is not performed when there is no utt2lid or utt2sid.
So I changed the strategy. Could you check my suggestion?

2022-09-02 00:20 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
>              if [ -e "${data_feats}/org/${dset}/utt2sid" ]; then
```suggestion
            _utt_extra_files=""
            if [ -e "${data_feats}/org/${dset}/utt2sid" ]; then
```

2022-09-02 00:20 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
> +                utils/fix_data_dir.sh --utt_extra_files utt2sid "${data_feats}/${dset}"
```suggestion
                _utt_extra_files+="utt2sid "
```

2022-09-02 00:20 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
> +                utils/fix_data_dir.sh --utt_extra_files utt2lid "${data_feats}/${dset}"
```suggestion
                _utt_extra_files+="utt2lid "
```

2022-09-02 00:20 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
```suggestion
            # shellcheck disable=SC2086
            utils/fix_data_dir.sh --utt_extra_files "${_utt_extra_files}" "${data_feats}/${dset}"
```

2022-09-02 04:19 UTC, jonghwanhyeon commented
No problem! Thanks 😄

2022-09-02 09:04 UTC, kan-bayashi commented on egs2/TEMPLATE/tts1/tts.sh
> +            utils/fix_data_dir.sh --utt_extra_files "${_utt_extra_files}" "${data_feats}/${dset}"
```suggestion
            utils/fix_data_dir.sh --utt_extra_files "${_utt_extra_files}" "${data_feats}/${dset}"

```

2022-09-05 00:00 UTC, kan-bayashi approved these changes

2022-09-05 00:01 UTC, merged

2022-09-05 00:01 UTC, kan-bayashi commented
Thank you for your kind contribution!