Add Talromur2 recipe
espnet/espnet pull request #4680
Opened 2022-09-30 20:06 UTC by G-Thor

This adds a recipe for the [Talrómur 2 multi-speaker corpus](https://repository.clarin.is/repository/xmlui/handle/20.500.12537/167). I've trained an [x-vector conditioned Tacotron 2](https://huggingface.co/espnet/talromur2_xvector_tacotron2) using this recipe with decent results.

The commit history is a bit messy so feel free to squash if you decide to merge this PR.

I'm open to any and all comments on how to improve this recipe.

2022-10-06 00:00 UTC, kan-bayashi requested changes
Sorry for the late review and thank you for adding a great recipe!
It looks almost perfect but I just left minor comments. Could you reflect them?

2022-10-06 00:00 UTC, kan-bayashi commented on .gitignore
> +tools/featbin*
Please add line break

2022-10-06 00:00 UTC, kan-bayashi commented on egs2/talromur2/tts1/local/data_download.sh
> +cd "${cwd}"
please add line break.

2022-10-06 00:00 UTC, kan-bayashi commented on egs2/talromur2/tts1/local/data_multi_speaker.sh
> +    ./local/split_train_dev_test.py --data_dir "data/${full_set}" --train_dir "data/${train_set}" --dev_dir "data/${dev_set}" --test_dir "data/${eval_set}"
```suggestion
    ./local/split_train_dev_test.py \
        --data_dir "data/${full_set}" \
        --train_dir "data/${train_set}" \
        --dev_dir "data/${dev_set}" \
        --test_dir "data/${eval_set}"
```

2022-10-06 00:00 UTC, kan-bayashi commented on egs2/talromur2/tts1/local/phonetize.sh
> +    ${train_cmd} --gpu 1 --num-threads 1 data/"${dset}_phn/log/conversion.log" ./pyscripts/utils/convert_text_to_phn.py --nj 1 --g2p g2p_is data/"${dset}"{,_phn}/text;
I think `--num-threads 1` is default.
```suggestion
    ${train_cmd} --gpu 1 data/"${dset}_phn/log/conversion.log" \
        ./pyscripts/utils/convert_text_to_phn.py \
            --nj 1 \
            --g2p g2p_is \
            data/"${dset}"{,_phn}/text
```

2022-10-06 00:00 UTC, kan-bayashi commented on egs2/talromur2/tts1/local/phonetize.sh
> +    # srun --gres=gpu:1 ./pyscripts/utils/convert_text_to_phn.py --nj 1 --g2p g2p_is --cleaner tacotron data/"${dset}"{,_phn}/text;
```suggestion
```

2022-10-06 00:00 UTC, kan-bayashi commented on egs2/talromur2/tts1/local/phonetize.sh
> +done
Please add line break.

2022-10-06 00:00 UTC, kan-bayashi commented on egs2/talromur2/tts1/run.sh
> +    # --srctexts "data/${train_set}/text" \
Please add line break.

2022-10-06 00:00 UTC, kan-bayashi commented on egs2/talromur2/tts1/train_multi_speaker_tacotron2.sh
> +    --inference_model valid.loss.ave_5best.pth
Please add line break.

2022-10-06 00:00 UTC, kan-bayashi commented on egs2/talromur2/tts1/train_multi_speaker_VITS.sh
> +#!/bin/bash
This is just my preference, but could use lower case? VITS -> vits

2022-10-29 01:42 UTC, kan-bayashi commented
Hi @G-Thor, we want to merge your great recipe.
You may struggle with ICASSP but could you reflect my review?

2022-11-07 12:30 UTC, G-Thor commented
Hi @kan-bayashi, thanks for your review. I've been on leave and waiting for updates to the official corpus repo.
I've now applied your suggested changes as well as removing some unused code.

I also went ahead and changed the installation of ice-g2p to use the official PyPI version of that package rather than my personal fork since my suggested changes to that project have been merged. I hope it is okay to apply this change here, but if it isn't, just lmk and I'll open a separate PR for that.

2022-11-08 00:20 UTC, kan-bayashi approved these changes
LGTM
Thank you for your great recipe :)

2022-11-08 00:21 UTC, merged